version: '3.7'
services:

  node-server:
    image: registry.todoent-dev.site/todoent
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: prod
      HOSTNAME: todoent-dev.site
      PORT: 3000
    restart: always
